apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    skip-clusterip-loadbalancer: "true"
    deployment.kubernetes.io/revision: "2"
  labels:
    app: tcp-server
  name: tcp-server
  namespace: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tcp-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tcp-server
    spec:
      containers:
      - image: princepereira/tcp-client-server:WS2019
        command: ["server.exe", "-p", "4444", "-pr", "All", "-swt", "5", "-awt", "5"]
        imagePullPolicy: Always
        name: tcpudpserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
        lifecycle:
          preStop:
            exec:
              command: ["curl", "--connect-timeout", "1000", "--max-time", "10000", "http://127.0.0.1:8090/kill", "-v"]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1000
      nodeSelector:
        kubernetes.azure.com/os-sku: Windows2019